# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q06mhnkze5ugU_V2uSWH3kqF8D8eJnvM
"""

import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

    def perimeter(self):
        return 2 * math.pi * self.radius


# Create object
r = float(input("Enter the radius of the circle: "))
c1 = Circle(r)

print("Area of the circle:", c1.area())
print("Perimeter of the circle:", c1.perimeter())